## Dodawanieinstalacja dockera  i dodanie wpisow do dnsow!##
- hosts: nodes
  become: yes
  tasks:
  - name: Instlacja dockera
    yum:
      name: docker
      state: latest
      update_cache: yes
  - name: Instalacja docker-compose
    shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
